export const products = [
    {
        id: 1,
        brand: "SAMSUNG",
        name: "CELULAR SAMSUNG GALAXY A12",
        desc: "Lorem ipsum",
        price: 31.999,
        img: "https://dummyimage.com/200/000/fff",
    },
    {
        id: 2,
        brand: "SAMSUNG",
        name: "CELULAR SAMSUNG A72",
        desc: "Lorem ipsum",
        price: 74.999,
        img: "https://dummyimage.com/200/000/fff",
    },
    {
        id: 3,
        brand: "SAMSUNG",
        name: "CELULAR SAMSUNG GALAXY S21 ULTRA",
        desc: "Lorem ipsum",
        price: 199.999,
        img: "https://dummyimage.com/200/000/fff",
    },
    {
        id: 4,
        brand: "MOTOROLA",
        name: "CELULAR MOTOROLA E7",
        desc: "Lorem ipsum",
        price: 23.999,
        img: "https://dummyimage.com/200/000/fff",
    },
    {
        id: 5,
        brand: "MOTOROLA",
        name: "CELULAR MOTOROLA MOTO G20 ",
        desc: "Lorem ipsum",
        price: 32.999,
        img: "https://dummyimage.com/200/000/fff",
    },
    {
        id: 6,
        brand: "MOTOROLA",
        name: "CELULAR MOTOROLA G100",
        desc: "Lorem ipsum",
        price: 93.999,
        img: "https://dummyimage.com/200/000/fff",
    },
    {
        id: 7,
        brand: "LG",
        name: "CELULAR LG K61 TITANIUM",
        desc: "Lorem ipsum",
        price: 30.999,
        img: "https://dummyimage.com/200/000/fff",
    },
    {
        id: 8,
        brand: "LG",
        name: "CELULAR LG VELVET",
        desc: "Lorem ipsum",
        price: 59.999,
        img: "https://dummyimage.com/200/000/fff",
    }
]